print("Hello")
raise Exception as se:
